# Generated by Django 4.1.1 on 2022-09-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_integer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='YearsServing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_serving_integer', models.IntegerField()),
            ],
        ),
    ]
